In [571]:
import numpy as np
from sklearn import datasets

In [572]:
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [573]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [574]:
iris.data.shape

(150, 4)

In [575]:
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [576]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [577]:
iris.target.shape

(150,)

In [578]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [579]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

### 拆分数据集

In [580]:
shuffle_index = np.random.permutation(len(y))
shuffle_index

array([  6,  34,  59, 104,  83,  22,  74, 142,   8,  44,  26, 100,  58,
        42,  61,  92, 144,  25,  87,  48, 108, 109,  68,  91,   4,  40,
        33, 134,  72,  13, 111, 130,  98,  51, 148,  81, 114,  85, 131,
        76,  62, 120,  53, 137, 129,  70, 138,  54, 124,   1,  11, 127,
        77,  35,  79, 105, 146,  10, 117,  28,  21,  23,  73,   0,  64,
       107,  86,  27,   7,  47,  63, 149, 141,  45,  12, 125, 136, 147,
       119,  67,  46,  55, 115, 126,  24,  36,  90,  57,  78,  15,  69,
        99,  38, 116,  66, 121,  96, 102, 106,  17,  95, 132,  88, 103,
        97,  39,  20,  71,   2,  30,  82,  75,  80, 110, 135,  89,  49,
        31, 133,  41,  52,  19, 112,  18, 140, 143,  16, 128,  84, 118,
        65, 101,  56,  14, 122,  32,  60, 123,  50,  43,  93,   9,  37,
       145,  94, 139,  29,   3, 113,   5], dtype=int32)

In [581]:
train_ratio = 0.8

In [582]:
train_size = int(len(y) * train_ratio)
train_size

120

In [583]:
train_index = shuffle_index[:train_size]
test_index = shuffle_index[train_size:]

In [584]:
X_train = X[train_index]
y_train = y[train_index]

X_test = X[test_index]
y_test = y[test_index]

In [585]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [586]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [587]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=666, shuffle=True, stratify=y)

In [588]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [589]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


### 预测

In [590]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=5)

In [591]:
knn_classifier.fit(X_train, y_train);

In [592]:
knn_classifier.score(X_test, y_test)

0.9333333333333333

In [593]:
y_predict = knn_classifier.predict(X_test)
y_predict

array([2, 0, 2, 1, 2, 0, 1, 2, 0, 0, 2, 1, 1, 2, 1, 0, 0, 1, 2, 0, 2, 0,
       2, 1, 0, 2, 1, 1, 1, 0])

### 评价

In [594]:
accuracy = np.sum(y_predict == y_test)/len(y_test)
accuracy

np.float64(0.9333333333333333)

In [595]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predict)

0.9333333333333333