In [141]:
import numpy as np
from sklearn import datasets

In [142]:
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [143]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [144]:
iris.data.shape

(150, 4)

In [145]:
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [146]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [147]:
iris.target.shape

(150,)

In [148]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [149]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

### 拆分数据集

In [150]:
shuffle_index = np.random.permutation(len(y))  # 随机生成0～149的不重复索引，用于打乱数据顺序
shuffle_index  # 查看打乱后的索引

array([ 81,  73,  17, 115, 105,  19,  63,   1,  83,  38,  42,  74,  57,
       118,  87,  52,  91,  50,  90,  75,  97,  98,  60, 125,  85,   0,
        16,  18,  22,  35,  66, 128,  32,  69, 130,  67,  93,  65,   8,
       139, 129, 132,  14,  95,  26, 136,  45, 126, 124,  10,  55,  61,
       106,  25,  23,   2, 117,  21, 103,  51,  29,   3,  78, 112, 143,
        53,  33, 146, 107,  12,  27,  15, 133, 140, 138, 104,  68,   5,
        34,  48,  79,  13, 116,  88, 144,  20,  44, 134,  84,   4, 123,
       141,  36,  31,  30,  46,  49,  72, 120,  71, 119,  28, 127,  64,
       142,  94, 122,  11, 114,   9, 109, 131, 113, 147,  39,  86,  92,
        96,  82,  76, 121, 101,  47,  58,  80, 145, 135,  70, 137, 110,
       102,  41, 111,  40,  77,  56,   6,  62,   7,  89, 108,  59,  37,
        54,  43, 149,  24,  99, 100, 148], dtype=int32)

In [151]:
train_ratio = 0.8  # 设置训练集比例为80%

In [152]:
train_size = int(len(y) * train_ratio)  # 计算训练集样本数量：150 × 0.8 = 120
train_size  # 查看训练集样本数量

120

In [153]:
train_index = shuffle_index[:train_size]  # 前120个索引作为训练集索引
test_index = shuffle_index[train_size:]   # 剩余30个索引作为测试集索引

In [154]:
X_train = X[train_index]   # 根据训练集索引提取特征数据
y_train = y[train_index]   # 根据训练集索引提取目标标签
X_test = X[test_index]     # 根据测试集索引提取特征数据
y_test = y[test_index]     # 根据测试集索引提取目标标签

In [155]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [156]:
# 使用 train_test_split 分层拆分训练集与测试集
from sklearn.model_selection import train_test_split  # 导入数据集拆分函数
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=666, shuffle=True, stratify=y)  # 按 8:2 的比例拆分训练集和测试集

In [157]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


### 预测

In [158]:
from sklearn.neighbors import KNeighborsClassifier  # 导入 KNN 分类模型
knn_classifier = KNeighborsClassifier(n_neighbors=5)  # 创建 KNN 分类器，设置邻居数量为 5

In [159]:
knn_classifier.fit(X_train, y_train);  # 使用训练集训练模型
knn_classifier.score(X_test, y_test)  # 计算模型在测试集上的准确率

0.9333333333333333

In [160]:
y_predict = knn_classifier.predict(X_test)  # 使用训练好的模型预测测试集类别
y_predict  # 查看预测结果

array([2, 0, 2, 1, 2, 0, 1, 2, 0, 0, 2, 1, 1, 2, 1, 0, 0, 1, 2, 0, 2, 0,
       2, 1, 0, 2, 1, 1, 1, 0])

### 评价

In [161]:
accuracy = np.sum(y_predict == y_test)/len(y_test)  # 手动计算预测准确率
accuracy  # 查看准确率

np.float64(0.9333333333333333)

In [162]:
from sklearn.metrics import accuracy_score  # 导入准确率评价函数
accuracy_score(y_test, y_predict)  # 使用 accuracy_score 计算预测准确率

0.9333333333333333