### 最大最小值归一化

In [174]:
import numpy as np
from sklearn import datasets

In [175]:
iris = datasets.load_iris()    # 加载鸢尾花数据集
X = iris.data
y = iris.target

In [176]:
X[:,0] = (X[:,0] - np.min(X[:,0])) / (np.max(X[:,0]) - np.min(X[:,0]))
X[:,1] = (X[:,1] - np.min(X[:,1])) / (np.max(X[:,1]) - np.min(X[:,1]))
X[:,2] = (X[:,2] - np.min(X[:,2])) / (np.max(X[:,2]) - np.min(X[:,2]))
X[:,3] = (X[:,3] - np.min(X[:,3])) / (np.max(X[:,3]) - np.min(X[:,3]))

In [177]:
X[:5]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667]])

### 零均值归一化

In [178]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [179]:
X[:,0] = (X[:,0] - np.mean(X[:,0])) / np.std(X[:,0])
X[:,1] = (X[:,1] - np.mean(X[:,1])) / np.std(X[:,1])
X[:,2] = (X[:,2] - np.mean(X[:,2])) / np.std(X[:,2])
X[:,3] = (X[:,3] - np.mean(X[:,3])) / np.std(X[:,3])

In [180]:
X[:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

### scikit-learn 中的 StandardScaler

In [181]:
from sklearn.preprocessing import StandardScaler

In [182]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [183]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [184]:
standard_scaler = StandardScaler()    # 创建 StandardScaler 标准化器
standard_scaler.fit(X);               # 根据 X 计算每个特征的均值和标准差

In [185]:
standard_scaler.mean_    # 查看每个特征的均值

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [186]:
standard_scaler.scale_   # 查看每个特征的标准差

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [187]:
X = standard_scaler.transform(X)    # 使用计算出的均值和标准差对 X 进行标准化
X[:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])