In [139]:
import numpy as np
from sklearn import datasets

In [140]:
iris = datasets.load_iris()  # 加载鸢尾花数据集
X = iris.data
y = iris.target.copy()
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [141]:
y[y != 0] = 1  # 转为二分类问题
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [142]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)
logistic_regression = LogisticRegression()
logistic_regression.fit(X_train, y_train)
y_predict = logistic_regression.predict(X_test)

### 手动计算 TN、FP、FN、TP、precision、recall、f1_score

In [143]:
TN = np.sum((y_predict == 0) & (y_test == 0))
TN

np.int64(10)

In [144]:
FP = np.sum((y_predict == 1) & (y_test == 0))
FP

np.int64(0)

In [145]:
FN = np.sum((y_predict == 0) & (y_test == 1))
FN

np.int64(0)

In [146]:
TP = np.sum((y_predict == 1) & (y_test == 1))
TP

np.int64(28)

In [147]:
confusion_matrix = np.array([
    [TN, FP],
    [FN, TP]
])
confusion_matrix

array([[10,  0],
       [ 0, 28]])

In [148]:
precision = TP / (FP + TP)
precision

np.float64(1.0)

In [149]:
recall = TP / (FN + TP)
recall

np.float64(1.0)

In [150]:
f1_score = 2 * precision * recall / (precision + recall)
f1_score

np.float64(1.0)

### sklearn中计算 TN、FP、FN、TP、precision、recall、f1_score

In [151]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_predict)

array([[10,  0],
       [ 0, 28]])

In [152]:
from sklearn.metrics import precision_score
precision_score(y_test, y_predict)

1.0

In [153]:
from sklearn.metrics import recall_score
recall_score(y_test, y_predict)

1.0

In [154]:
from sklearn.metrics import f1_score
f1_score(y_test, y_predict)

1.0

In [155]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predict)

1.0