### 张量的保存和加载

In [114]:
import torch

In [115]:
a = torch.rand(6)
a

tensor([0.7894, 0.6432, 0.3311, 0.9364, 0.2815, 0.7871])

In [116]:
torch.save(a, "model/tensor_a")

In [117]:
torch.load("model/tensor_a")

tensor([0.7894, 0.6432, 0.3311, 0.9364, 0.2815, 0.7871])

In [118]:
a = torch.rand(6)
b = torch.rand(6)
c = torch.rand(6)
[a, b, c]

[tensor([0.0471, 0.9367, 0.5200, 0.8752, 0.8354, 0.2611]),
 tensor([0.9876, 0.2711, 0.8612, 0.6310, 0.6853, 0.6269]),
 tensor([0.6077, 0.0363, 0.1203, 0.3374, 0.6385, 0.5813])]

In [119]:
torch.save([a, b, c], "model/tensor_abc")

In [120]:
torch.load("model/tensor_abc")

[tensor([0.0471, 0.9367, 0.5200, 0.8752, 0.8354, 0.2611]),
 tensor([0.9876, 0.2711, 0.8612, 0.6310, 0.6853, 0.6269]),
 tensor([0.6077, 0.0363, 0.1203, 0.3374, 0.6385, 0.5813])]

In [121]:
tensor_dict = {'a': a, 'b': b, 'c': c}
tensor_dict

{'a': tensor([0.0471, 0.9367, 0.5200, 0.8752, 0.8354, 0.2611]),
 'b': tensor([0.9876, 0.2711, 0.8612, 0.6310, 0.6853, 0.6269]),
 'c': tensor([0.6077, 0.0363, 0.1203, 0.3374, 0.6385, 0.5813])}

In [122]:
torch.save(tensor_dict, "model/tensor_dict_abc")

In [123]:
torch.load("model/tensor_dict_abc")

{'a': tensor([0.0471, 0.9367, 0.5200, 0.8752, 0.8354, 0.2611]),
 'b': tensor([0.9876, 0.2711, 0.8612, 0.6310, 0.6853, 0.6269]),
 'c': tensor([0.6077, 0.0363, 0.1203, 0.3374, 0.6385, 0.5813])}

### 模型的保存和加载

In [124]:
from torchvision import datasets  # 常用图像数据集，如 MNIST、CIFAR-10
from torchvision import transforms  # 图像预处理和数据增强工具
import torch.nn as nn  # 神经网络模块，用于定义网络层和损失函数
import torch.optim as optim  # 优化器模块，用于更新模型参数

class MLP(nn.Module):  # 定义一个多层感知机（MLP）模型，定义一个名为 MLP 的类，并让它继承 PyTorch 的 nn.Module 类。
    # 定义 MLP 类的初始化方法，input_size输入数据的维度，hidden_size 隐藏层的大小，num_classes 输出分类的数量
    def __init__(self, input_size, hidden_size, num_classes):
        super().__init__()  # 初始化父类 nn.Module
        self.fc1 = nn.Linear(input_size, hidden_size)       # 第1个全连接层：输入层 → 隐藏层
        self.relu = nn.ReLU()                               # ReLU 激活函数
        self.fc2 = nn.Linear(hidden_size, hidden_size)      # 第2个全连接层：隐藏层 → 隐藏层
        self.fc3 = nn.Linear(hidden_size, num_classes)      # 输出层：隐藏层 → 分类结果

    def forward(self, x):       # 定义数据在网络中的前向传播过程
        out = self.fc1(x)       # 输入数据经过第1个全连接层
        out = self.relu(out)    # 使用 ReLU 激活函数
        out = self.fc2(out)     # 经过第2个全连接层
        out = self.relu(out)    # 再次使用 ReLU 激活函数
        out = self.fc3(out)     # 经过输出层，得到各类别的输出值
        return out              # 返回模型的最终输出

input_size = 28 * 28   # 输入维度：MNIST 图片为 28×28，展开后共 784 个特征
hidden_size = 512      # 隐藏层神经元数量
num_classes = 10       # 输出类别数量：数字 0~9，共 10 类

model = MLP(input_size, hidden_size, num_classes)  # 创建 MLP 模型实例

### 方式1（推荐）

In [125]:
# 保存模型参数（只保存参数，不保存整个模型结构）
torch.save(model.state_dict(), "model/mlp_state_dict.pth")

In [126]:
# 读取之前保存的模型参数
mlp_state_dict = torch.load("model/mlp_state_dict.pth")

# 重新实例化一个与原模型结构完全相同的 MLP
model_load = MLP(input_size, hidden_size, num_classes)

# 将读取到的参数加载到新模型中
model_load.load_state_dict(mlp_state_dict)

<All keys matched successfully>

### 方式2（不推荐）

In [127]:
# 保存整个模型，会同时保存模型结构和模型参数
torch.save(model, "model/mlp_model.pth")

In [128]:
# 加载整个模型，不需要重新实例化模型，也不需要手动调用 load_state_dict()
mlp_load = torch.load("model/mlp_model.pth", weights_only=False)